testing deploy

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,6 +34,10 @@ jobs:
               cd api
                sudo dotnet restore
                sudo dotnet publish -c Release
+               if [ $? -ne 0 ]; then
+                  echo "dotnet publish failed"
+                  exit 1
+               fi
                cd api/bin/Release/net8.0/publish
                nohup sudo dotnet api.dll &
             fi
